#!/usr/bin/env bash
# cc-stack:commit-gate v1 — installed by cc-stack, do not edit this file in place.
# ─────────────────────────────────────────────────────────────────────────────
# THE COMMIT GATE. A worktree sub-task may not commit without the human's authorization; that red
# line is otherwise prose only, and a sub-task in auto mode has been observed committing anyway.
# Scope: checkouts under .claude/worktrees/ or .worktrees/. The primary checkout is untouched.
#
# Grant: the parent session (relaying the human's authorization) creates a sentinel at the
# worktree root:
#     touch <worktree>/.commit-authorized
# CONSUMED on each allowed commit — one grant, one commit. If the commit then fails (e.g. the
# project's own commit-msg hook rejects it), the grant is spent; re-touch to retry.
#
# WHY THIS IS A GIT HOOK AND NOT A PreToolUse HOOK (migrated 2026-08-16, feat/commit-gate-git).
# The predecessor (hooks/block-worktree-commit.sh, retired) parsed the TEXT of every Bash command
# and guessed the commit's effective directory out of it. That is the same class of parser that
# docs/known-issues.md retired on the tab-close side, and it failed the same two ways on one day:
#   • mis-BLOCKED prose — a brief or a heredoc whose body merely quoted `git … commit` (twice: a
#     sub-task writing a file, and a probe whose commits all lived in a /tmp repo);
#   • mis-ALLOWED the real thing — `git -C "$W" commit` reached the parser as the literal three
#     characters `$W` (no variable expansion in a hook), which is not a directory, so it fell back
#     to the session cwd, saw the primary checkout, and waved the commit through unread.
# git's own pre-commit hook has neither problem: it never sees command text, and it runs with cwd
# already set to the worktree that is actually committing — whatever syntax got git there.
#
# WHY .git/hooks/ AND NOT core.hooksPath (live-probed 2026-08-16, git 2.55.0/darwin):
#   • core.hooksPath silently REPLACES the whole downstream hook set — a repo enforcing
#     Conventional Commits through its own commit-msg loses it without a word. Excluded outright.
#   • .git/hooks/ is shared by every linked worktree of the repo, so mounting is once per REPO,
#     not once per worktree.
# A pre-commit that already existed is preserved next door as `pre-commit.cc-stack-orig` and
# exec'd from here once the gate passes, so the project's own hook still runs (see the mount
# logic in cc-dispatch.sh commit-gate).
#
# ACCEPTED RESIDUE — `git commit --no-verify` bypasses this completely (probed: it commits
# silently). That is DELIBERATE and is not worth new machinery: the retired PreToolUse version was
# equally bypassable (a shell function, a script file, a variable naming the directory — the main
# session went through it unintentionally on 2026-08-16). This gate stops a slip of the hand and a
# skill acting on its own initiative. It is not a security boundary and must not be sold as one.
set -u
# NOTE: the marker string in the header line above is how the mount logic recognises its own hook
# (ours → replace on upgrade; anyone else's → preserve and chain), and the suite counts it to prove
# a re-mount never nests a second copy of this body. It must appear exactly ONCE in this file —
# don't reword it and don't quote it again anywhere below.

# Where git found this hook — a chained predecessor lives next to it. `--git-path hooks` is the
# authority (it also answers correctly from a linked worktree, whose own .git is a FILE); $0 is
# only a fallback because git passes it RELATIVE from a main checkout and absolute from a worktree.
_ccg_hooks="$(git rev-parse --git-path hooks 2>/dev/null)"
[ -n "$_ccg_hooks" ] || _ccg_hooks="$(dirname -- "$0")"
_ccg_next="$_ccg_hooks/pre-commit.cc-stack-orig"

# Hand off to the project's own pre-commit, if we displaced one. Not executable = git would have
# ignored it too, so we do the same. This is the LAST thing the gate does on every allowed path.
_ccg_chain() {
  [ -x "$_ccg_next" ] && exec "$_ccg_next" ${1+"$@"}
  exit 0
}

# The committing worktree. git runs hooks with cwd at the top of the working tree, so this is the
# real target no matter how the command spelled it (`cd X && git commit`, `git -C "$VAR" commit`,
# a shell function, a script file). Both the raw and the symlink-resolved form are checked below:
# a match on EITHER gates the commit, so a /tmp-vs-/private/tmp style alias can never open a hole.
_ccg_top="$(git rev-parse --show-toplevel 2>/dev/null)"
[ -n "$_ccg_top" ] || _ccg_top="$PWD"
_ccg_real="$( (CDPATH= cd -- "$_ccg_top" 2>/dev/null && pwd -P) 2>/dev/null )"

_ccg_gated=""
for _ccg_d in "$_ccg_top" "$_ccg_real"; do
  [ -n "$_ccg_d" ] || continue
  case "$_ccg_d" in
    */.claude/worktrees/*|*/.worktrees/*) _ccg_gated=1 ;;
  esac
done
[ -n "$_ccg_gated" ] || _ccg_chain ${1+"$@"}       # primary checkout / any other repo: not our business

# Sentinel, checked under both spellings of the root for the same reason the scope test is.
_ccg_sentinel="$_ccg_top/.commit-authorized"
for _ccg_d in "$_ccg_top" "$_ccg_real"; do
  [ -n "$_ccg_d" ] || continue
  if [ -f "$_ccg_d/.commit-authorized" ]; then
    rm -f "$_ccg_d/.commit-authorized"             # one grant, one commit
    _ccg_chain ${1+"$@"}
  fi
done

echo "✗ cc-stack commit gate: git commit inside a worktree sub-task requires the human's authorization." >&2
echo "  Stop and report back instead — the default posture is 'keep the branch, don't land'." >&2
echo "  Parent session, once the human has authorized it, grants exactly ONE commit with:" >&2
echo "      touch $_ccg_sentinel" >&2
exit 1
